# NUMPY

In [6]:
#Print all output statements
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Library import
import numpy as np

## Numbers generation
* Same of Python `range` method, Numpy provides the `arange` and `linspace` method.
* It's not a good idea to use `arange` with floating point arguments, use linspace instead.

In [14]:
# Examples:
a = np.arange(10)
b = np.linspace(1, 10, 3)
type(a), type(b)
a, b

(numpy.ndarray, numpy.ndarray)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 1. ,  5.5, 10. ]))

## Arrays

The main object in Numpy is the homogeneous multidimensional array, `ndarray`. This object contains an array defined with:

* Dimensions are called *axes* (2-D, 3-D, etc...).
* The *shape* of a multidimensional array corresponds with the lenght of each *axe* (3x3, 4x5, 3x3x3).

It also have pre-defined print methods for a nice looking into the output.

### Creation
To build an array you can use `np.array` to create a new array object from a Python list or tuple or a pre-defined Numpy array

* `zeros(tuple-shape)`
* `ones(tuple-shape)`
* `empty(tuple-shape)`

In [49]:
A_from_tuple = np.array((1,2,3,4))
A_from_list = np.array([[1,2,3,4], [1,2,3,4]])

z = np.zeros((3,3,3))
A_from_tuple
z.shape
type(z)
print(z)

#Shape of the array, dimensions, datatype, total num. elements
z.shape, z.ndim, z.dtype.name, z.size

array([1, 2, 3, 4])

(3, 3, 3)

numpy.ndarray

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


((3, 3, 3), 3, 'float64', 27)

### Indexin, slicing and iterating

Arrays can be accessed, depending the dimensions of the array:

* One-dimensional arrays: Accessed like python list.
* Multi-dimensional arrays: Accessed with one index per axis, separated with commas.

Arrays can be iterated with the Python `for` statement (iterate per row) or with the `flat` method (iterate each element).


In [64]:
a = np.arange(20).reshape(2,10)
a
a[1,4]
a[:,3]

for row in a:
    print(row)
for element in a.flat:
    print(element, end=" ")

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

14

array([ 3, 13])

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

### Basic operations

The arrays can operated with different operators; the results are stored into a new array object.

* Arithmetic element-wise operators: `+`,`-`,`/`,`*`,`**`
* Boolean element-wise operators: Greather than, Greather or equal than, equal than, less than, etc...
* Matrix product operator: `@`
* Universal functions `ufunc`: Mathematical functions as `sin`, `cos`, `exp`, etc...

> Attention: Be careful with the shapes of the operands!

![Alt text](resources/numpy_ufunc.png)

There are also array operations:

* reshape: `.reshape(new-shape)` With an axe with -1 the other is automatically calculated.
* transpose: `.T`
* flatten: `.ravel()`
* Stack arrays same axes: Can be added vertically `vstack` or horitzonall `hstack`.
* Stack 1D arrays: `column_stack` will stack 1D arrays into 2D arrays.
* Split arrays: `np.hsplit()` will split horitzonal and `np.vsplit()`


In [65]:
A = np.arange(4)
B = np.arange(5, 9)
A, B
C = A+B
C

(array([0, 1, 2, 3]), array([5, 6, 7, 8]))

array([ 5,  7,  9, 11])

### Numpy object copies
* Simple assignments **doesn't make a copy**.
* `view()` method creates an new array object that **points to the same data**.
* `copy()` method creates a deep copy of the object, so **it doesn't point to the same data**.
* An array slicing also returns a `view` to the initial array object.
> REMEMBER: Python passes mutable objects as references, function call make no copies.

In [78]:
A = np.arange(4)
B = A #This is a view!
C = A.copy() #This is a copy!
id(A) == id(B)
id(A) == id(C)
print(A, B, C)
A[3] = 33
print(A, B, C)

True

False

[0 1 2 3] [0 1 2 3] [0 1 2 3]
[ 0  1  2 33] [ 0  1  2 33] [0 1 2 3]
